name: lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: lint proto files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lint proto
        run: |
          make lint

  generate-check:
    name: check build proto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: build proto
        run: |
          make gen

      - name: verify change code
        run: |
          git add .
          git diff --staged --exit-code || (git diff --staged && exit 1)